version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/gevg/bit
    steps:
      - checkout
      - run: go get -v -d ./...
      - run: go test -v -race ./...