version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/gevg/bit
    steps:
      - checkout
      - run: go get -v -d ./...
      - run: go test -cover -v -race -coverprofile=./coverage.out ./...
      - run: go get github.com/mattn/goveralls
      - run: goveralls -coverprofile=./coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN